version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/static
    ports:
      - 8080:80
    depends_on:
      - flask_app
    restart: "on-failure"

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/static
    expose:
      - 5000

volumes:
  static_volume:
